Adding a Default Action in 12-cmdline.md solution fails on piped stdin
Solution readings09.py fails on piped stdin and no action argument:
``` bash
python ../code/readings_09.py < small-01.csv
Traceback (most recent call last):
  File "../code/readings_09.py", line 33, in <module>
    main()
  File "../code/readings_09.py", line 7, in main
    action = sys.argv[1]
IndexError: list index out of range
```
This error occurs because there is no argument for action or filename. The fix adds a conditional test to handle the case where no args exist. 

The `readings_09.py` file in the `code` folder would also need to be updated for this fix.